### ISSUE TITLE
About your GitHub username

### ISSUE THREAD

**Issue by risenxxx** [risen/invoicer#1]
Hello! Sorry for this way of communication (I mean your repo's issues)

I like your GitHub username (I use it all over the internet for many years), and I would be very happy if I could buy it for GitHub too.

Maybe it sounds not very nice, and I hope this didn't offend you.

If you don't mind selling your username, please write to the mail to@risen.dev, or reply to this issue.

Thank you for your time!

**Comment by risen** [comment]
Replied via twitter
